name: Post Football News to Twitter

on:
  schedule:
    - cron: '30 2,6,12,16 * * *'
  workflow_dispatch:

jobs:
  post-news:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create posted_urls.txt if it doesn't exist
      run: touch posted_urls.txt

    - name: Run football news bot
      env:
        # Use the exact secret names from your GitHub repository
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      run: |
        python main.py

    - name: Upload posted URLs as artifact (for debugging)
      uses: actions/upload-artifact@v4
      with:
        name: posted-urls
        path: posted_urls.txt
        if-no-files-found: ignore
