name: Post football news daily
on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          NUM_TWEETS: ${{ secrets.NUM_TWEETS }}
          POST_WITH_IMAGE: ${{ secrets.POST_WITH_IMAGE }}
          BASE_HASHTAGS: ${{ secrets.BASE_HASHTAGS }}
