name: Post Football News to X

on:
  schedule:
    # 10:00, 14:00, 18:00, 22:00 IST = 04:30, 08:30, 12:30, 16:30 UTC
    - cron: '30 4 * * *'
    - cron: '30 8 * * *'
    - cron: '30 12 * * *'
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  post-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: python main.py

      - name: Commit posted_goal_urls.txt changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_goal_urls.txt
          git commit -m "Update posted URLs [bot]" || echo "No changes to commit"
          git push || echo "No changes to push"
